FROM node:18-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install && npm install -g next
COPY . .
RUN npm run build

FROM nginx:stable-alpine AS production
COPY --from=build /app/out /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]